name: Check links in Markdown files
on:
  schedule:
    - cron: 0 0 * * 1   # midnight every Monday
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  check-links:
    name: Linkspector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_level: any
